name: production-deploy

on:
  pull_request:
    branches: [ master ]
    types: [closed]
jobs:
  if: github.event.pull_request.merged == true
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script: |
            cd /var/www/html/
            git pull
