name: deploy-stating

on:
  pull_request:
    branches: 
      - develop
    types: [closed]

jobs:
  if: github.event.pull_request.merged == true
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd /var/www/html/
            git pull
